model:
  name: denoising_diffusion_pytorch.simple_diffusion.UViT
  params:
    dim: 128
    dim_mults: [1, 2, 4, 8]


diffusion:
  name: denoising_diffusion_pytorch.simple_diffusion.GaussianDiffusion
  params:
    image_size: 128
    noise_d: 64